services:
  - type: web
    name: ucsd-x-crs-recruitment-chatbot
    runtime: node
    rootDir: chat-server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
