services:
  - type: web
    name: ucsd-x-crs-website
    runtime: node
    rootDir: chat-server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: GOOGLE_DRIVE_FOLDER_ID
        value: 1x1aL_4j-xgzGf7idPT1DWSgjzr1GN8CF
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
